from process_functions import *

rules = {
    'head_01': {'function': head_01, 'parts': ['headline'], 'ruleDesc': 'Headlines should not exceeed 70 characters', },
    'head_06': {'function': head_06, 'parts': ['headline'], 'ruleDesc': 'Headlines shouldnt have long words'},
    'head_09': {'function': head_09, 'parts': ['headline'], 'ruleDesc': 'Headlines should have single quotes and not double quotes'},
    'head_10': {'function': head_10, 'parts': ['headline'], 'ruleDesc': 'Headlines should use en dash and not hyphen or colon when indicating source'},
    'head_11': {'function': head_11, 'parts': ['headline'], 'ruleDesc': 'Headlines should use digits and not spelled out except for zero'},
    'head_12': {'function': head_12, 'parts': ['headline'], 'ruleDesc': 'Headline word after colon should be capitalized'},
    'subhead_01': {'function': subhead_01, 'parts': ['subhead'], 'ruleDesc': 'Subhead should not exceed 200 characters'},
    'subhead_06': {'function': subhead_06, 'parts': ['subhead'], 'ruleDesc': 'Subhead should have single quotes and not double quotes'},
    'dateline_03': {'function': dateline_03, 'parts': ['body'], 'ruleDesc': 'Metro Manila Dateline should use MANILA, PHILIPPINES'},
    # 'breaker_01': {'function': breaker_01, 'parts': ['headline', 'body'], 'ruleDesc': 'Breakers should be in H5 format'},
    'breaker_02': {'function': breaker_02, 'parts': ['body'], 'ruleDesc': 'Breakers should not exceed 4 words'},
    'breaker_05': {'function': breaker_05, 'parts': ['body'], 'ruleDesc': 'Beakers use single quotes, not double quotes or italics'},
    'url_01': {'function': url_01, 'parts': ['url'], 'ruleDesc': 'URLs should have 11 words max'},
    'url_04': {'function': url_04, 'parts': ['url'], 'ruleDesc': 'URLs should not have punctuations'},
    'url_06': {'function': url_06, 'parts': ['url'], 'ruleDesc': 'URLs should not begin with a number'},
    'name_01': {'function': name_01, 'parts': ['headline', 'body'], 'ruleDesc': 'Put periods in honorifics and suffixes, Mr Mrs Dr Jr Sr'},
    'name_02': {'function': name_02, 'parts': ['headline', 'body'], 'ruleDesc': 'Put periods in middle initials'},
    'name_03': {'function': name_03, 'parts': ['headline', 'body'], 'ruleDesc': 'Sr. And Jr. should not have a comma separating it from the surname'},
    'name_04': {'function': name_04, 'parts': ['headline', 'body'], 'ruleDesc': 'Don’t put periods in names like TJ, AJ, JC, etc.'},
    'name_05': {'function': name_05, 'parts': ['headline', 'body'], 'ruleDesc': 'Names with de, dela, de la, del, de los, delos should not be capitalized if the first name is mentioned'},
    'position_05': {'function': position_05, 'parts': ['headline', 'body'], 'ruleDesc': 'Use lowercase for opposition senator and opposition lawmaker, whether with a name or not.'},
    'position_09': {'function': position_09, 'parts': ['headline', 'body'], 'ruleDesc': 'There is no hyphen in vice president, vice governor, vice mayor, etc.'},
    'position_10': {'function': position_10, 'parts': ['headline', 'body'], 'ruleDesc': 'Use foreign secretary, not foreign affairs secretary'},
    'position_12': {'function': position_12, 'parts': ['headline', 'body'], 'ruleDesc': 'When using then-(position), there should be a hyphen. Lowercase for the position.'},
    'position_21': {'function': position_21, 'parts': ['headline', 'body'], 'ruleDesc': 'The Pope and the Dalai Lama are always capitalized.'},
    'agency_03': {'function': agency_03, 'parts': ['body'], 'ruleDesc': 'If the full name and the acronym will be used in the same sentence, don’t put the acronym in parentheses next to the first mention.'},
    'agency_05': {'function': agency_05, 'parts': ['body'], 'ruleDesc': 'No need to put the acronyms in parentheses for the United Nations and the European Union.'},
    'agency_09': {'function': agency_09, 'parts': ['body'], 'ruleDesc': 'Senate and House of Representatives should always be capitalized'},
    'agency_12': {'function': agency_12, 'parts': ['body'], 'ruleDesc': 'Use non-government organization, not non-governmental'},
    'place_06': {'function': place_06, 'parts': ['body'], 'ruleDesc': 'Spell out st., rd., ave., and blvd (street, avenue, road, boulevard)'},
    'dates_01': {'function': dates_01, 'parts': ['body'], 'ruleDesc': 'Spell out days and months'},
    'dates_02': {'function': dates_02, 'parts': ['body'], 'ruleDesc': 'Day format on first mention: day of week, comma, month & Day'},
    'dates_03': {'function': dates_03, 'parts': ['body'], 'ruleDesc': 'Never use yesterday, today, tomorrow, last week, last month, last year, next week, next month, next year'},
    'dates_04': {'function': dates_04, 'parts': ['body'], 'ruleDesc': 'Data format is Month Day, Year'},
    'dates_05': {'function': dates_05, 'parts': ['body'], 'ruleDesc': 'Use "in month year"'},
    'dates_06': {'function': dates_06, 'parts': ['body'], 'ruleDesc': 'When referring to decades, use yyyy-s'},
    'dates_07': {'function': dates_07, 'parts': ['body'], 'ruleDesc': 'nth year anniversary is wrong'},
    'dates_08': {'function': dates_08, 'parts': ['body'], 'ruleDesc': 'for am/pm, dont use periods'},
    'dates_09': {'function': dates_09, 'parts': ['body'], 'ruleDesc': 'if at top of the hour, no need to use :00'},
    'dates_10': {'function': dates_10, 'parts': ['body'], 'ruleDesc': "don't include 12 if using noon or midnight"},
    'numbers_01': {'function': numbers_01, 'parts': ['headline', 'body'], 'ruleDesc': 'The general rule for exact numbers is to spell out zero to nine and use digits for 10 onwards'},
    'numbers_02': {'function': numbers_02, 'parts': ['headline', 'body'], 'ruleDesc': 'When describing age, use the format x-year-old but only if it is an adjective'},
    'numbers_03': {'function': numbers_03, 'parts': ['headline', 'body'], 'ruleDesc': 'if using digits in a phrase, use only digits and not spelled out numbers'},
    'numbers_04': {'function': numbers_04, 'parts': ['headline', 'body'], 'ruleDesc': 'If a sentence begins with a number, spell it out, unless it is a year'},
    'numbers_05': {'function': numbers_05, 'parts': ['headline', 'body'], 'ruleDesc': 'When describing number ranges, use "to" and not hyphen'},
    'numbers_06': {'function': numbers_06, 'parts': ['headline', 'body'], 'ruleDesc': 'Spell out first to ninth unless it is describing a congressional district, court, division, or military unit'},
    'numbers_07': {'function': numbers_07, 'parts': ['headline', 'body'], 'ruleDesc': 'For top <number>, the word top is lowercase.'},
    'numbers_08': {'function': numbers_08, 'parts': ['headline', 'body'], 'ruleDesc': 'using No. X should always be capitalized'},
    'numbers_09': {'function': numbers_09, 'parts': ['headline', 'body'], 'ruleDesc': 'Never use XX-k to refer to thousands'},
    'numbers_10': {'function': numbers_10, 'parts': ['headline', 'body'], 'ruleDesc': 'Use % and not percent, also separated by a space'},
    'numbers_11': {'function': numbers_11, 'parts': ['headline', 'body'], 'ruleDesc': 'No need for .0 in percentages'},
    'numbers_12': {'function': numbers_12, 'parts': ['headline', 'body'], 'ruleDesc': 'Spell out fractions'},
    'numbers_13': {'function': numbers_13, 'parts': ['headline', 'body'], 'ruleDesc': 'Use P instead of Php, without space, $ and not USD'},
    'numbers_14': {'function': numbers_14, 'parts': ['headline', 'body'], 'ruleDesc': 'multimillion, multibillion has no hyphen'},
    'numbers_15': {'function': numbers_15, 'parts': ['headline', 'body'], 'ruleDesc': 'Use km/h not kph'},
    'numbers_16': {'function': numbers_16, 'parts': ['headline', 'body'], 'ruleDesc': 'Use kWh not kwh'},
    'numbers_17': {'function': numbers_17, 'parts': ['headline', 'body'], 'ruleDesc': 'For internet speeds, put a space between the number and the unit of measurement'},
    'numbers_18': {'function': numbers_18, 'parts': ['headline', 'body'], 'ruleDesc': 'For temperatures, go straight to °C and °F.'},
    'numbers_19': {'function': numbers_19, 'parts': ['headline', 'body'], 'ruleDesc': 'Use Roman numerals for World War I and World War II.'},
    'grammar_01': {'function': grammar_01, 'parts': ['headline', 'body'], 'ruleDesc': 'use results in, not results to'},
    'grammar_02': {'function': grammar_02, 'parts': ['headline', 'body'], 'ruleDesc': 'dont use "for" after seek/sought'},
    'grammar_03': {'function': grammar_03, 'parts': ['headline', 'body'], 'ruleDesc': 'dont use "as" after called/dubbed'},
    'grammar_04': {'function': grammar_04, 'parts': ['headline', 'body'], 'ruleDesc': '"on the other hand" should have "on the one hand" in the same paragraph'},
    'punctuation_01': {'function': punctuation_01, 'parts': ['headline', 'body'], 'ruleDesc': 'Use the Oxford or serial comma'},
    'punctuation_02': {'function': punctuation_02, 'parts': ['headline', 'body'], 'ruleDesc': 'Capitalization after a colon:'},
    'punctuation_03': {'function': punctuation_03, 'parts': ['headline', 'body'], 'ruleDesc': 'A dash is used to separate word/s. We commonly use the en dash (–), not the em dash (—), with spaces'},
    'punctuation_04': {'function': punctuation_04, 'parts': ['headline', 'body'], 'ruleDesc': 'When words end with s, use just an apostrophe for the possessive form.'},
    'politicolegal_01': {'function': politicolegal_01, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s charged with, not charged of'},
    'politicolegal_02': {'function': politicolegal_02, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s indicted for, not indicted of.'},
    'politicolegal_03': {'function': politicolegal_03, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s plead guilty to, not plead guilty of.'},
    'politicolegal_04': {'function': politicolegal_04, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s convicted of and acquitted of, not for'},
    'politicolegal_07': {'function': politicolegal_07, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s right against self-incrimination, not right to self-incrimination'},
    'politicolegal_15': {'function': politicolegal_15, 'parts': ['headline', 'body'], 'ruleDesc': 'Show cause order, temporary restraining order, writ of amparo, writ of habeas corpus, writ of kalikasan, affidavit, and other similar documents or orders are lowercase.'},
    'disasters_02': {'function': disasters_02, 'parts': ['headline', 'body'], 'ruleDesc': 'Various weather systems are lowercase (tropical cyclone, low pressure area, intertropical convergence zone (ITCZ), southwest monsoon, northeast monsoon, tail-end of a frontal system, easterlies, etc.)'},
    'disasters_07': {'function': disasters_07, 'parts': ['headline', 'body'], 'ruleDesc': 'Use earthquake (not quake) in headlines and URLs. Quake is acceptable in the body'},
    'disasters_09': {'function': disasters_09, 'parts': ['headline', 'body'], 'ruleDesc': 'For volcanoes, spell out Mount and not Mt.'},
    'health_01': {'function': health_01, 'parts': ['headline', 'body'], 'ruleDesc': 'By definition, a pandemic is global. Global pandemic is redundant. Just say pandemic'},
    'health_02': {'function': health_02, 'parts': ['headline', 'body'], 'ruleDesc': 'Coronavirus is acceptable on first mention. Add “the” (the coronavirus).'},
    'health_03': {'function': health_03, 'parts': ['headline', 'body'], 'ruleDesc': "Use COVID-19, not Covid-19, not COVID, not Covid. There is no 'the' before COVID-19"},
    'race_02': {'function': race_02, 'parts': ['headline', 'body'], 'ruleDesc': 'The plural form of Lumad is still Lumad, not Lumads'},
    'race_04': {'function': race_04, 'parts': ['headline', 'body'], 'ruleDesc': 'Capitalize Black when referring to the race as a noun or adjective'},
    'gender_02': {'function': gender_02, 'parts': ['headline', 'body'], 'ruleDesc': 'It’s trans man or transgender man and trans woman or transgender woman. Never use transman or transwoman.'},
    'gender_03': {'function': gender_03, 'parts': ['headline', 'body'], 'ruleDesc': 'Transgender is an adjective. Do not use it as a noun'},
    'gender_04': {'function': gender_04, 'parts': ['headline', 'body'], 'ruleDesc': 'Use them, they, their instead of the clunky he/she and him/her'},
    'photos_01': {'function': photos_01, 'parts': ['headline', 'body'], 'ruleDesc': 'Each photo caption begins with a title in all caps, no more than two words, followed by a period. The title should be closely related to the photo.'},
    'photos_02': {'function': photos_02, 'parts': ['headline', 'body'], 'ruleDesc': 'Photo caption should only be one sentence.'},
    'photos_05': {'function': photos_05, 'parts': ['headline', 'body'], 'ruleDesc': 'Photo caption should use single and not double quotation marks'},
    'photos_06': {'function': photos_06, 'parts': ['headline', 'body'], 'ruleDesc': 'Photo caption date format should be Month Day, Year'},
    'photos_08': {'function': photos_08, 'parts': ['headline', 'body'], 'ruleDesc': 'Photo credits should not contain "Photo by" and go straight to the name of the photographer.'},
    'photos_12': {'function': photos_12, 'parts': ['headline', 'body'], 'ruleDesc': 'Reuters photos should use Name/Reuters or Original Source/Reuters'},
    'photos_15': {'function': photos_15, 'parts': ['headline', 'body'], 'ruleDesc': 'If the photo is a screenshot from a video, put Rappler video screenshot or Name of Source video screenshot. Don’t use “screengrab”'},
    'photos_16': {'function': photos_16, 'parts': ['headline', 'body'], 'ruleDesc': 'When in doubt about the source of a photo or you’re unsure who to credit, do not use.'},
    'hyperlinks_01': {'function': hyperlinks_01, 'parts': ['headline', 'body'], 'ruleDesc': 'Put hyperlinks in stories whenever applicable. Aim for at least 3 or more'}
}

def agg_details(input_content):
    details = []
    for rulename in rules.keys():
        fulltext = ' '.join(input_content[i] for i in rules[rulename]['parts'])
        result = rules[rulename]['function'](fulltext)
        
        details.append({
            'ruleCode': rulename,
            'ruleResult': 'FAIL' if len(result) > 0 else 'PASS',
            'resultDesc': rules[rulename]['ruleDesc'],
            'offendingStrings': result
        })
    return details
